// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDily2Uv0B2yVUqxURkteuEo1QSD1GMEyY',
    appId: '1:774748773484:web:8869d10409ad626960cc49',
    messagingSenderId: '774748773484',
    projectId: 'expense-tracker-4f75e',
    authDomain: 'expense-tracker-4f75e.firebaseapp.com',
    storageBucket: 'expense-tracker-4f75e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhA3OArX45Cfy3ykv0wRJMrm6F_Q1QhMk',
    appId: '1:774748773484:android:bd2eb557967e870860cc49',
    messagingSenderId: '774748773484',
    projectId: 'expense-tracker-4f75e',
    storageBucket: 'expense-tracker-4f75e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBtZ4uu6O0K7aKKvpp4_VLptdamlBocw0',
    appId: '1:774748773484:ios:eab4cc37ccc3808360cc49',
    messagingSenderId: '774748773484',
    projectId: 'expense-tracker-4f75e',
    storageBucket: 'expense-tracker-4f75e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBtZ4uu6O0K7aKKvpp4_VLptdamlBocw0',
    appId: '1:774748773484:ios:eab4cc37ccc3808360cc49',
    messagingSenderId: '774748773484',
    projectId: 'expense-tracker-4f75e',
    storageBucket: 'expense-tracker-4f75e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDily2Uv0B2yVUqxURkteuEo1QSD1GMEyY',
    appId: '1:774748773484:web:9e4f1776733da04760cc49',
    messagingSenderId: '774748773484',
    projectId: 'expense-tracker-4f75e',
    authDomain: 'expense-tracker-4f75e.firebaseapp.com',
    storageBucket: 'expense-tracker-4f75e.firebasestorage.app',
  );
}
